apiVersion: v1
kind: Service
metadata:
  name: db #cuz the worker pod will read it as db so if named it "postgers" for example the connection of the database will fail
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
    